# Generated by Django 4.1 on 2024-04-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0008_alter_distributor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='na_tusd_in_reais_per_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='off_peak_te_in_reais_per_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='off_peak_tusd_in_reais_per_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='off_peak_tusd_in_reais_per_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='peak_te_in_reais_per_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='peak_tusd_in_reais_per_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='peak_tusd_in_reais_per_mwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
