# Generated by Django 4.1 on 2024-06-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0009_alter_tariff_na_tusd_in_reais_per_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='is_in_new_resolution',
            field=models.BooleanField(default=True),
        ),
    ]
