# Generated by Django 4.1 on 2024-07-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0010_distributor_is_in_new_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='power_generation_tusd_in_reais_per_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
