# Generated by Django 4.1 on 2024-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0011_tariff_power_generation_tusd_in_reais_per_kw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='power_generation_tusd_in_reais_per_kw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
