# Generated by Django 4.1 on 2024-06-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_password_status',
            field=models.CharField(choices=[('OK', 'OK'), ('admin_reset', 'admin_reset'), ('user_reset', 'user_reset')], default='OK', max_length=25),
        ),
    ]
