# Generated by Django 4.1 on 2024-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_account_password_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_password_status',
            field=models.CharField(choices=[('OK', 'OK'), ('first_access', 'first_access'), ('admin_reset', 'admin_reset'), ('user_reset', 'user_reset')], default='OK', max_length=25),
        ),
    ]
