# Generated by Django 4.1 on 2024-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_account_password_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_seed_user',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
