# Generated by Django 5.1.1 on 2024-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usertoken_invalid_tried_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('super_user', 'super_user'), ('university_admin', 'university_admin'), ('university_spectator', 'university_spectator'), ('university_user', 'university_user')], max_length=25),
        ),
    ]
