
services:
  mepa-api:
    container_name: mepa-api
    restart: unless-stopped
    image: mepa-api:latest-test
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - DJANGO_ENV=${ENVIRONMENT:-test}
    env_file: 
      - ./.envs/.env.test
    command: ['sh', 'scripts/start_prod.sh']
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - api-network
      - web-network
    depends_on:
      - mepa-db

  mepa-db:
    container_name: mepa-db
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION}
    env_file: 
      - ./.envs/.env.test
    volumes:
      - mepa-test-data:/var/lib/postgresql/data
    networks:
      - api-network

volumes:
  mepa-test-data:
    name: mepa-test-data

networks:
  api-network:
    name: api-network
    driver: bridge
  web-network:
    name: web-network
    driver: bridge
