# Generated by Django 4.1 on 2024-08-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_merge_20231115_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energybill',
            name='off_peak_consumption_in_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='energybill',
            name='off_peak_measured_demand_in_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='energybill',
            name='peak_consumption_in_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='energybill',
            name='peak_measured_demand_in_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
