# Generated by Django 4.1 on 2024-05-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_alter_consumerunit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerunit',
            name='total_installed_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potência total de geração de energia instalada em kw', max_digits=6, null=True),
        ),
    ]
