# Generated by Django 4.1 on 2024-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_consumerunit_total_installed_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunit',
            name='code',
            field=models.CharField(help_text='Cheque a conta de luz para obter o código da Unidade Consumidora. Insira apenas números', max_length=30, verbose_name='Código da Unidade Consumidora'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='name',
            field=models.CharField(help_text='Nome da Unidade Consumidora. Ex: Darcy Ribeiro', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterUniqueTogether(
            name='consumerunit',
            unique_together={('university', 'code', 'name')},
        ),
    ]
