# Generated by Django 4.1 on 2024-08-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_alter_consumerunit_code_alter_consumerunit_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumerunit',
            unique_together={('university', 'code')},
        ),
    ]
