# Generated by Django 4.1 on 2024-08-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_alter_consumerunit_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumerunit',
            unique_together={('university', 'name', 'code')},
        ),
    ]
