# Generated by Django 4.1 on 2024-09-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0013_alter_consumerunit_total_installed_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunit',
            name='name',
            field=models.CharField(help_text='Nome da Unidade Consumidora. Ex: Darcy Ribeiro', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(help_text='Nome da universidade por extenso', max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
